In [4]:
import tkinter as tk
from tkinter import filedialog
from PIL import Image, ImageTk
import numpy as np
from keras.models import load_model
from keras.preprocessing import image as keras_image

# Load the pre-trained model
model = load_model('model_pneu.h5')  # Update with your model path
class_names = ['Normal', 'Pneumonia']  # Update with your class names

# Function to predict class
def predict_class(image_path):
    img = keras_image.load_img(image_path, target_size=(150, 150))  # Adjust target_size if necessary
    img_array = keras_image.img_to_array(img)
    img_array = np.expand_dims(img_array, axis=0)
#     img_array /= 255.  # Normalize pixel values
    prediction = model.predict(img_array)
    print(prediction)
    prediction = list(prediction[0])
    predicted_class_index = prediction.index(max(prediction))
#     predicted_class_index = np.argmax(prediction)
    predicted_class = class_names[predicted_class_index]
    return predicted_class

# Function to open file dialog and display selected image
def select_image():
    file_path = filedialog.askopenfilename()
    if file_path:
        predicted_class = predict_class(file_path)
        label.config(text="Predicted class: " + predicted_class)
        img = Image.open(file_path)
        img = img.resize((150, 150))  # Adjust image size as needed
        photo = ImageTk.PhotoImage(img)
        panel.config(image=photo)
        panel.image = photo

# Create GUI
root = tk.Tk()
root.title("Image Classifier")

# Button to select image
select_button = tk.Button(root, text="Select Image", command=select_image)
select_button.pack(pady=10)

# Panel to display selected image
panel = tk.Label(root)
panel.pack()

# Label to display predicted class
label = tk.Label(root, text="")
label.pack(pady=10)

root.mainloop()

1/1 [==============================] - 0s 386ms/step
[[0.7466623  0.25333765]]
1/1 [==============================] - 0s 63ms/step
[[0.7172803  0.28271964]]
1/1 [==============================] - 0s 62ms/step
[[0.39310306 0.60689694]]
1/1 [==============================] - 0s 70ms/step
[[0.78849477 0.21150528]]
1/1 [==============================] - 0s 79ms/step
[[0.7466623  0.25333765]]
1/1 [==============================] - 0s 79ms/step
[[0.6156731 0.3843269]]
1/1 [==============================] - 0s 79ms/step
[[0.3261576 0.6738424]]
1/1 [==============================] - 0s 78ms/step
[[0.3261576 0.6738424]]
1/1 [==============================] - 0s 62ms/step
[[0.35185647 0.64814353]]
1/1 [==============================] - 0s 60ms/step
[[0.20892341 0.7910766 ]]
1/1 [==============================] - 0s 72ms/step
[[0.39310306 0.60689694]]
1/1 [==============================] - 0s 100ms/step
[[0.7172803  0.28271964]]
1/1 [==============================] - 0s 86ms/step
[[0.7466623  0.2